# Generated by Django 2.2.4 on 2020-05-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_tv_shows_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tv_shows',
            name='releasedate',
            field=models.DateField(),
        ),
    ]
