# Generated by Django 2.2.4 on 2020-05-26 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('trip', '0002_trips_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='user',
        ),
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('joiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_left', to='login.user')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='trip.Trips')),
            ],
        ),
    ]
