// <auto-generated />
using System;
using CRUDelicious.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CRUDelicious.Migrations
{
    [DbContext(typeof(CRUDeliciousContext))]
    [Migration("20200612023524_deletedcreatedate")]
    partial class deletedcreatedate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CRUDelicious.Models.Dish", b =>
                {
                    b.Property<int>("DishrId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Calories");

                    b.Property<string>("CheifName")
                        .IsRequired();

                    b.Property<string>("Description");

                    b.Property<string>("DishName")
                        .IsRequired();

                    b.Property<int>("TasteRating");

                    b.HasKey("DishrId");

                    b.ToTable("Dishs");
                });

            modelBuilder.Entity("CRUDelicious.Models.User", b =>
                {
                    b.Property<int>("DishrId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("DishrId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
