# Generated by Django 2.2.4 on 2020-05-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200511_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=55)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Wizard',
        ),
    ]
