# Generated by Django 2.2.4 on 2020-05-18 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firsname',
            new_name='firstname',
        ),
    ]
