# Generated by Django 2.2.4 on 2020-05-12 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dojo',
            old_name='location',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='ninja',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='dojo',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dojo',
            name='state',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ninja',
            name='lastname',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ninja',
            name='ninja_in_dojo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ninja_location', to='app1.dojo'),
            preserve_default=False,
        ),
    ]
