# Generated by Django 2.2.4 on 2020-05-19 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wall_message',
            name='user',
        ),
        migrations.DeleteModel(
            name='wall_comment',
        ),
        migrations.DeleteModel(
            name='wall_message',
        ),
    ]
