# Generated by Django 2.2.4 on 2020-05-22 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('app', '0004_quotes_numoflikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotes',
            name='numoflikes',
        ),
        migrations.CreateModel(
            name='likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField()),
                ('quotes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='login.user')),
            ],
        ),
    ]
