# Generated by Django 2.2.4 on 2020-05-22 21:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200522_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='like',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='likes',
        ),
    ]
