# Generated by Django 2.2.4 on 2020-05-22 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200522_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotes',
            old_name='like',
            new_name='rating',
        ),
    ]
