# Generated by Django 2.2.4 on 2020-05-22 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200522_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotes',
            name='rating',
        ),
    ]
