# Generated by Django 2.2.4 on 2020-05-22 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_quotes_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotes',
            name='like',
        ),
    ]
